# Generated by Django 4.1.13 on 2026-03-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shortcut_token',
            field=models.CharField(blank=True, default='', help_text='Long-lived token for Siri Shortcuts. Regenerate to revoke access.', max_length=64, verbose_name='Siri Shortcut Token'),
        ),
    ]
