# Generated by Django 4.1.13 on 2026-03-26 06:03

from django.db import migrations, models


def empty_to_null(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(shortcut_token='').update(shortcut_token=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_shortcut_token'),
    ]

    operations = [
        # First allow NULL values (do not add the unique constraint yet) so we can
        # safely convert empty-string values to NULL in a following data migration.
        migrations.AlterField(
            model_name='customuser',
            name='shortcut_token',
            field=models.CharField(blank=True, default=None, help_text='Long-lived token for Siri Shortcuts. Regenerate to revoke access.', max_length=64, null=True, unique=False, verbose_name='Siri Shortcut Token'),
        ),
        migrations.RunPython(empty_to_null, migrations.RunPython.noop),
        # Now enforce uniqueness once empty strings have been converted to NULL.
        migrations.AlterField(
            model_name='customuser',
            name='shortcut_token',
            field=models.CharField(blank=True, default=None, help_text='Long-lived token for Siri Shortcuts. Regenerate to revoke access.', max_length=64, null=True, unique=True, verbose_name='Siri Shortcut Token'),
        ),
    ]
