# Generated by Django 4.1.13 on 2026-03-26 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_shortcut_token_null_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notify_on_armed', models.BooleanField(default=True)),
                ('notify_on_siren', models.BooleanField(default=True)),
                ('notify_on_panic', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fcm_token')},
            },
        ),
    ]
