# Generated by Django 4.1.5 on 2023-02-18 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicableArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField(unique=True, verbose_name='Applicable AREA ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Applicable Area',
                'verbose_name_plural': 'Applicable Areas',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True, verbose_name='Event ID')),
                ('description', models.CharField(max_length=50, verbose_name='Event Description')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Event Type Name')),
                ('range_begin', models.IntegerField(default=-1, verbose_name='Start of Included Event IDs')),
                ('range_end', models.IntegerField(default=-1, verbose_name='End of Included Event IDs')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(unique=True, verbose_name='Zone ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('sealed', models.IntegerField(default=-1, verbose_name='Current State of Zone (Sealed/Unsealed)')),
                ('excluded', models.BooleanField(default=False, verbose_name='Zone Excluded')),
                ('zone_address', models.IntegerField(default=0, verbose_name='Zone Address')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hide from display')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.CharField(default='', max_length=50, verbose_name='Raw Data')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp')),
                ('byte_start', models.IntegerField(default=-1, verbose_name='Start Byte')),
                ('byte_address', models.IntegerField(default=-1, verbose_name='Address')),
                ('byte_length', models.IntegerField(default=-1, verbose_name='Length')),
                ('byte_command', models.IntegerField(default=-1, verbose_name='Command')),
                ('checksum', models.IntegerField(default=-1, verbose_name='Checksum Byte')),
                ('applicable_id', models.IntegerField(blank=True, null=True, verbose_name='Applicable ID')),
                ('input_command_received', models.BooleanField(default=False, help_text='Has this event been received by the Ness Security System', verbose_name='Received')),
                ('data', models.CharField(default='', max_length=60, verbose_name='Data Field')),
                ('applicable_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ness.applicablearea', to_field='area_id', verbose_name='Applicable AREA')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ness.event', to_field='event_id', verbose_name='General EVENTS')),
            ],
            options={
                'verbose_name': 'Event Data',
                'verbose_name_plural': 'Event Data',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ness.eventtype'),
        ),
    ]
