# Generated by Django 4.1.5 on 2023-03-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='user_input_command',
            field=models.BooleanField(default=False, help_text='Is this a user input command?', verbose_name='User Input Command'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='input_command_received',
            field=models.BooleanField(default=False, help_text='Has this event been received by the Ness Security System?', verbose_name='Received'),
        ),
    ]
