# Generated by Django 4.1.5 on 2023-03-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0004_remove_eventdata_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicableArea',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
