# Generated by Django 4.1.5 on 2023-03-04 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0005_delete_applicablearea_delete_event_delete_eventtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventData',
            new_name='Event',
        ),
    ]
