# Generated by Django 4.1.5 on 2023-03-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0007_event_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Type ID'),
        ),
    ]
