version: '3.8'

services:

  django:
    image: ness_web:django
    build: ./NessWebServer
    env_file:
      - .env
    volumes:
      - ./NessWebServer:/NessWebServer
      - ./log/gunicorn/:/var/log/gunicorn/
    ports:
      - "8011:8000"
    networks:
      - default

  nginx:
    image: nginx:latest
    build: ./nginx
    depends_on:
      - django
    ports:
      - "62:80"
    volumes:
      - ./NessWebServer/static-files:/var/www/static
      - ./NessWebServer/media-files:/var/www/media
      - ./log/nginx/:/var/log/nginx/
    networks:
      - default

networks:
  default:
