services:

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  django:
    image: ness_web:django
    build: ./NessWebServer
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    volumes:
      - ./NessWebServer:/NessWebServer
      - static_files:/app/static-files
      - media_files:/app/media-files
      - log_gunicorn:/var/log/gunicorn/
    ports:
      - "8011:8000"
    depends_on:
      - redis
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  nginx:
    image: ness_web:nginx
    build: ./nginx
    depends_on:
      - django
    ports:
      - "62:80"
    volumes:
      - static_files:/var/www/static
      - media_files:/var/www/media
      - log_nginx:/var/log/nginx/
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  log_gunicorn:
  log_nginx:
  static_files:
  media_files:

networks:
  default:
