# Generated by Django 5.2.4 on 2025-07-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default='', max_length=50, verbose_name='Device Name')),
                ('ip', models.CharField(default='', max_length=50, verbose_name='IP Address')),
                ('software_version', models.CharField(default='', max_length=50, verbose_name='Software Version')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.CharField(default='', max_length=50, verbose_name='Raw Data')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('type_id', models.IntegerField(blank=True, null=True, verbose_name='Type ID')),
                ('data', models.CharField(max_length=60, verbose_name='Data Field')),
                ('user_input_command', models.BooleanField(default=False, help_text='Is this a user input command?', verbose_name='User Input Command')),
                ('input_command_received', models.BooleanField(default=False, help_text='Has this event been received by the Ness Security System?', verbose_name='Received')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(unique=True, verbose_name='Zone ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('sealed', models.IntegerField(default=-1, verbose_name='Current State of Zone (Sealed/Unsealed)')),
                ('excluded', models.BooleanField(default=False, verbose_name='Zone Excluded')),
                ('zone_address', models.IntegerField(default=0, verbose_name='Zone Address')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hide from display')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
    ]
