# Generated by Django 5.2.4 on 2025-07-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ness2wifi_ip', models.CharField(default='', max_length=50, verbose_name='Ness WiFi IP')),
                ('ness2wifi_fw_version', models.CharField(default='', max_length=50, verbose_name='Ness 2 WiFi bridge Firmware Version')),
                ('is_armed_home', models.BooleanField(default=False)),
                ('is_armed_away', models.BooleanField(default=False)),
                ('is_disarmed', models.BooleanField(default=False)),
                ('arming_delayed_active', models.BooleanField(default=False)),
                ('alarm_siren_on', models.BooleanField(default=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Status',
                'verbose_name_plural': 'System Status',
            },
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.CharField(default='', max_length=50, verbose_name='Raw Data')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('type_id', models.IntegerField(blank=True, null=True, verbose_name='Type ID')),
                ('data', models.CharField(max_length=60, verbose_name='Data Field')),
                ('user_input_command', models.BooleanField(default=False, help_text='Is this a user input command?', verbose_name='User Input Command')),
                ('input_command_received', models.BooleanField(default=False, help_text='Has this event been received by the Ness Security System?', verbose_name='Received')),
            ],
            options={
                'verbose_name': 'User Input',
                'verbose_name_plural': 'User Inputs',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Zone Name, displayed to the user')),
                ('sealed', models.IntegerField(default=-1, verbose_name='Current State of Zone (Sealed/Unsealed)')),
                ('excluded', models.BooleanField(default=False, verbose_name='Zone Excluded')),
                ('address', models.IntegerField(default=0, verbose_name='Zone Address, unique from the nessclient lib')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hide from the user display')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
    ]
