# Generated by Django 5.2.4 on 2025-07-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ness_comms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='UserInput',
        ),
    ]
