# Generated by Django 4.1.13 on 2026-03-21 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ness_comms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ZONE_SEALED', 'Zone Sealed'), ('ZONE_TRIGGERED', 'Zone Triggered'), ('ZONE_EXCLUDED', 'Zone Excluded'), ('ZONE_INCLUDED', 'Zone Included'), ('ARMED_AWAY', 'Armed Away'), ('ARMED_HOME', 'Armed Home'), ('DISARMED', 'Disarmed'), ('SIREN_ON', 'Siren Activated'), ('SIREN_OFF', 'Siren Deactivated'), ('PANIC_TRIGGERED', 'Panic Triggered')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(blank=True, default='', max_length=200)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ness_comms.zone')),
            ],
            options={
                'verbose_name': 'Alarm Event',
                'verbose_name_plural': 'Alarm Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
