# Generated by Django 4.1.13 on 2026-03-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness_comms', '0002_alarmevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('secret', models.CharField(blank=True, default='', help_text='Optional. If set, a X-Ness-Signature header (HMAC-SHA256) is added to each request.', max_length=200, verbose_name='HMAC Secret')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('send_all_events', models.BooleanField(default=False, help_text='If checked, all event types are sent. Otherwise only the event types listed below are sent.', verbose_name='Send All Events')),
                ('events', models.JSONField(blank=True, default=list, help_text='List of event type strings (e.g. ["ARMED_AWAY", "SIREN_ON"]). Ignored if Send All Events is checked.', verbose_name='Event Types')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
            },
        ),
    ]
