# Generated by Django 5.2.4 on 2025-07-12 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ness_comms', '0002_rename_event_userinput'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemstatus',
            options={'verbose_name': 'System Status', 'verbose_name_plural': 'System Status'},
        ),
        migrations.AlterModelOptions(
            name='userinput',
            options={'verbose_name': 'User Input', 'verbose_name_plural': 'User Inputs'},
        ),
    ]
