# Generated by Django 5.0 on 2023-12-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='code_line',
            field=models.IntegerField(verbose_name='Code Line'),
        ),
    ]
