# Generated by Django 4.1.5 on 2023-03-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=150, verbose_name='Function')),
                ('description', models.TextField(verbose_name='Description')),
                ('code_line', models.IntegerField(verbose_name='Code Line)')),
                ('file_name', models.CharField(max_length=150, verbose_name='Function')),
            ],
            options={
                'verbose_name': 'Error',
                'verbose_name_plural': 'Error',
            },
        ),
    ]
