# Generated by Django 4.1.5 on 2023-01-31 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicableArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField(unique=True, verbose_name='Applicable AREA ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Applicable Area',
                'verbose_name_plural': 'Applicable Areas',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True, verbose_name='Event ID')),
                ('description', models.CharField(max_length=50, verbose_name='Event Description')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Event Type Name')),
                ('range', models.IntegerField(verbose_name='Event ID Range')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='User ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='User Name')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(unique=True, verbose_name='Zone ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.CreateModel(
            name='OutputEventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.CharField(max_length=50, verbose_name='Raw Data')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp')),
                ('applicable_id', models.TextField(blank=True, null=True, verbose_name='Applicable ID')),
                ('applicable_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ness.applicablearea', verbose_name='Applicable AREA')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ness.event', verbose_name='Zone or User EVENTS')),
            ],
            options={
                'verbose_name': 'Output Event Data',
                'verbose_name_plural': 'Output Event Data',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ness.eventtype'),
        ),
    ]
