# Generated by Django 4.1.5 on 2023-01-31 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputeventdata',
            name='applicable_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ness.applicablearea', verbose_name='Applicable AREA'),
        ),
        migrations.AlterField(
            model_name='outputeventdata',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ness.event', verbose_name='Zone or User EVENTS'),
        ),
    ]
