# Generated by Django 4.1.5 on 2023-02-01 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0002_alter_outputeventdata_applicable_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='applicable_id',
            field=models.IntegerField(default=0, verbose_name='Applicable ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outputeventdata',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ness.event', verbose_name='General EVENTS'),
        ),
    ]
