# Generated by Django 4.1.5 on 2023-03-04 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0002_eventdata_user_input_command_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdata',
            old_name='byte_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='eventdata',
            old_name='byte_command',
            new_name='command',
        ),
        migrations.RenameField(
            model_name='eventdata',
            old_name='byte_length',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='eventdata',
            old_name='byte_start',
            new_name='start',
        ),
    ]
