# Generated by Django 4.1.5 on 2023-02-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0003_event_applicable_id_alter_outputeventdata_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='applicable_id',
        ),
    ]
