# Generated by Django 4.1.5 on 2023-03-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0003_rename_byte_address_eventdata_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='applicable_area',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='applicable_id',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='command',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='length',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='start',
        ),
        migrations.AddField(
            model_name='eventdata',
            name='type',
            field=models.CharField(default='', max_length=50, verbose_name='Type'),
        ),
    ]
