# Generated by Django 4.1.5 on 2023-02-01 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0004_remove_event_applicable_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outputeventdata',
            old_name='applicable_id',
            new_name='applicable_id_description',
        ),
    ]
