# Generated by Django 4.1.5 on 2023-02-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0005_rename_applicable_id_outputeventdata_applicable_id_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputeventdata',
            name='applicable_id',
            field=models.IntegerField(default=0, verbose_name='Applicable ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outputeventdata',
            name='applicable_id_description',
            field=models.TextField(blank=True, null=True, verbose_name='Applicable ID Description'),
        ),
    ]
