# Generated by Django 4.1.5 on 2023-02-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0006_outputeventdata_applicable_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputeventdata',
            name='applicable_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Applicable ID'),
        ),
    ]
