# Generated by Django 4.1.5 on 2023-03-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0006_rename_eventdata_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type_id',
            field=models.IntegerField(default=-1, verbose_name='Type ID'),
        ),
    ]
