# Generated by Django 4.1.5 on 2023-02-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0007_alter_outputeventdata_applicable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='sealed',
            field=models.BooleanField(default=False, verbose_name='Current State of Zone (Sealed/Unsealed)'),
        ),
    ]
