# Generated by Django 4.1.5 on 2023-03-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0008_alter_event_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Type'),
        ),
    ]
