# Generated by Django 4.1.5 on 2023-02-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0008_zone_sealed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='sealed',
            field=models.IntegerField(default=-1, verbose_name='Current State of Zone (Sealed/Unsealed)'),
        ),
    ]
