# Generated by Django 4.1.5 on 2023-02-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0009_alter_zone_sealed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='range',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='range_begin',
            field=models.IntegerField(default=-1, verbose_name='Start of Included Event IDs'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='range_end',
            field=models.IntegerField(default=-1, verbose_name='End of Included Event IDs'),
        ),
    ]
