# Generated by Django 4.1.5 on 2023-02-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0010_remove_eventtype_range_eventtype_range_begin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
