# Generated by Django 4.1.5 on 2023-03-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0010_alter_event_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
