# Generated by Django 4.1.5 on 2023-02-02 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0011_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=-1, verbose_name='Current State of Alarm (Armed/Not Armed/Unknown)')),
                ('area_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ness.event', verbose_name='Area Event')),
            ],
            options={
                'verbose_name': 'Armed',
                'verbose_name_plural': 'Armed',
            },
        ),
    ]
