# Generated by Django 4.1.5 on 2023-12-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0011_alter_event_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default='', max_length=50, verbose_name='Device Name')),
                ('ip', models.CharField(default='', max_length=50, verbose_name='IP Address')),
                ('software_version', models.CharField(default='', max_length=50, verbose_name='Software Version')),
            ],
        ),
    ]
