# Generated by Django 4.1.5 on 2023-02-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0012_armed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Armed',
        ),
    ]
