# Generated by Django 4.1.5 on 2023-02-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0013_delete_armed'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputeventdata',
            name='received_by_ness',
            field=models.BooleanField(default=False, help_text='Has this event been received by the Ness Security System', verbose_name='Received by Alarm System'),
        ),
    ]
