# Generated by Django 4.1.5 on 2023-02-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0014_outputeventdata_received_by_ness'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputeventdata',
            name='byte_address',
            field=models.IntegerField(default=-1, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='outputeventdata',
            name='byte_command',
            field=models.IntegerField(default=-1, verbose_name='Command'),
        ),
        migrations.AddField(
            model_name='outputeventdata',
            name='byte_length',
            field=models.IntegerField(default=-1, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='outputeventdata',
            name='byte_start',
            field=models.IntegerField(default=-1, verbose_name='Start Byte'),
        ),
        migrations.AddField(
            model_name='outputeventdata',
            name='checksum',
            field=models.IntegerField(default=-1, verbose_name='Checksum Byte'),
        ),
        migrations.AddField(
            model_name='outputeventdata',
            name='data',
            field=models.CharField(default='', help_text='Bytes are coded in ASCII. E.g. -> 0x54 = 54', max_length=60, verbose_name='ASCII Data'),
        ),
    ]
