# Generated by Django 4.1.5 on 2023-02-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0015_outputeventdata_byte_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputeventdata',
            name='raw_data',
            field=models.CharField(default='', max_length=50, verbose_name='Raw Data'),
        ),
    ]
